---
- name: Launch an EC2 instance with specific configuration
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 instance
      ec2:
        key_name: mykey
        instance_type: t2.xlarge
        image: ami-058b428b3b45defec  
        region: us-east-1
        wait: yes
        group: application_sg  
        instance_tags:
          Name: application
        exact_count: 1
        count_tag:
          Name: application
        volumes:
          - device_name: /dev/sda1
            volume_size: 50
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Display instance public IP
      debug:
        msg: "EC2 instance is up and running at {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
